dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- coverage run -m unittest discover && coverage report
after_success:
- coveralls
deploy:
  provider: pypi
  user: stblassitude
  password:
    secure: AlHLXOVE7GQhy7RVocIQPHbEFwvWX0eadr9k55ZGyeK9TTr/KxvjbQxy7hPgitUK7zJCqkmQ9qiJUOlHkVXTZyNsTF/sRLEm6Ma8hR8dH8eCmMZhWAN8etAXv2NgJIqcFHtr6caiq4vRl/WK6jY/dNMXYSi03M6J85qRJFlqDBHBmlh3/cDvWuyGYloS83rsHgroKUbG7/SU9iIyQTdxjb+IgLd5jeSBTDAcIavhFCeKlL6R1lcCCwYzaqAN1beQLHouwgCggq6y4TdwF1U7CaTgRnFs9c+jF4j4G80VNs1AWY57VTW+mmnZ+7tzFl1apP24xHFypSCJ5TxY0lueKi++t9b4dkqPm0ZlJf37erjlHeHtBMLqFouydViONFewllLGoZq1+IlFyhJV2yt6feKT960KCNU/mpqPIx9k2w8+4XN3vfwpPLp62G5zmwrqKrDqV7+jU35tw0bcGrr96TXddu2YMq7iop9fCFinyA4hrX12xJFe8TcPJV2wgRwetXvf4zW3WqAwRHWFSu8HoK+d6doliWJUvSxq+EIT4ELMMgHkV5maU3/Wr8Q3vr5nN6ELcLwiR+2f8nwcoHbJt1nJMyMKVkIIFkICvQVluGGrDZ2VnbBTWjniUw1uCbeJafYjUvMXsfby1wqFwU97TazxdIMl5fC/TAi2qkzQCCc=
  on:
    branch: master
